version: '3.9'
services:
    practica-nginx:
        container_name: practica-nginx
        restart: unless-stopped
        build:
            context: ./
            dockerfile: docker/nginx/Dockerfile
        volumes:
            - ./:/var/www
            - ./docker/nginx/${DOMAIN_VHOST_FILE}:/etc/nginx/conf.d/custom.conf
        ports:
            - "80"
        links:
            - practica-php
        environment:
            VIRTUAL_HOST: ${DOMAIN_HOSTS}
            VIRTUAL_PORT: 80
            LETSENCRYPT_HOST: ${DOMAIN_HOSTS}
            LETSENCRYPT_EMAIL: ${DOMAIN_EMAIL}
        networks:
            - nginx-proxy
            - practica

    practica-php:
        user: ${USER_ID}:${GROUP_ID}
        container_name: practica-php
        restart: unless-stopped
        build:
            context: ./
            dockerfile: docker/php/Dockerfile
            args:
                USER_ID: ${USER_ID}
                GROUP_ID: ${GROUP_ID}
        volumes:
            - ./:/var/www
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - ./docker/php/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
        tmpfs:
            - /dev/shm
        links:
            - practica-mysql
            - practica-redis
        ports:
            - ${XDEBUG_EXTERNAL_PORT}:9003
            - ${VITE_PORT}
        extra_hosts:
            - ${EXTRA_HOST_FRONTEND}
            - "host.docker.internal:host-gateway"
        networks:
            - nginx-proxy
            - practica

    practica-mysql:
        container_name: practica-mysql
        restart: unless-stopped
        image: mysql:8.0.33
        volumes:
            - ./docker/mysql/mysql.conf:/etc/mysql/conf.d/myconf.conf
            - ./docker/mysql/init:/docker-entrypoint-initdb.d
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ports:
            - ${MYSQL_EXTERNAL_PORT}:3306
        networks:
            - practica

    practica-redis:
        container_name: practica-redis
        restart: unless-stopped
        build:
            args:
                REDIS_PASSWORD: ${REDIS_PASSWORD}
            context: ./
            dockerfile: docker/redis/Dockerfile
        ports:
            - ${REDIS_EXTERNAL_PORT}:6379
        sysctls:
            - net.core.somaxconn=511
        networks:
            - practica

networks:
    practica:
    nginx-proxy:
        external: true
